name: polymer_app_layout_demos
version: 0.0.2
description: Web demo of the polymer_app_layout package

environment:
  sdk: '>1.16.0-dev.5.5 <2.0.0' #https://github.com/dart-lang/sdk/issues/26228

dependencies:
  browser: ^0.10.0
  polymer: ^1.0.0-rc.16
  polymer_app_layout: ^0.0.5
  web_components: ^0.12.0
  route_hierarchical:
  dart_to_js_script_rewriter: ^1.0.1
dev_dependencies:
  ghpages_generator: 
transformers:
- polymer:
    entry_points:
    - web/index.html
    - web/demo/demo1.html
    - web/demo/demo2.html
    - web/demo/demo3.html

    - web/app-box/demo/document_scroll.html
    - web/app-box/demo/scrolling_region.html
    - web/app-drawer/demo/demo1.html
    - web/app-drawer/demo/demo2.html
    - web/app-drawer-layout/demo/demo1.html
    - web/app-drawer-layout/demo/demo2.html
    - web/app-header/demo/contacts.html
    - web/app-header/demo/demo1.html
    - web/app-header/demo/demo2.html
    - web/app-header/demo/demo3.html
    - web/app-header/demo/give.html
    - web/app-header/demo/music.html
    - web/app-header/demo/no-effects.html
    - web/app-header/demo/notes.html
    - web/app-header/demo/pesto.html
    - web/app-header-layout/demo/demo1.html
    - web/app-header-layout/demo/demo2.html
    - web/app-header-layout/demo/music.html
    - web/app-scrollpos-control/demo/index.html
    - web/app-toolbar/demo/index.html

    - web/templates/test_drive/index.html
    - web/templates/getting_started/index.html
    - web/templates/landing_page/index.html
    - web/templates/pesto/index.html
    - web/templates/shrine/index.html
    - web/patterns/transform_navigation/index.html
    - web/patterns/expand_card/index.html
- dart_to_js_script_rewriter
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
