name: polymer_app_layout_demos
version: 0.0.1
description: Web demos of the polymer_app_layout package

environment:
  sdk: '>1.16.0-dev.5.5 <2.0.0' #https://github.com/dart-lang/sdk/issues/26228

dependencies:
  browser: ^0.10.0
  polymer: ^1.0.0-rc.16
  polymer_app_layout: 0.0.1
  web_components: ^0.12.0
  dart_to_js_script_rewriter: ^1.0.1
dev_dependencies:
  ghpages_generator: 
transformers:
- polymer:
    entry_points:
    - web/index.html
    - web/demo/demo1.html
    - web/demo/demo2.html
    - web/demo/demo3.html
    - web/app-box/demo/document_scroll.html
    - web/app-box/demo/scrolling_region.html
    - web/templates/test_drive/index.html
    - web/templates/getting_started/index.html
    - web/templates/landing_page/index.html
    - web/patterns/transform_navigation/index.html
    - web/patterns/expand_card/index.html
- dart_to_js_script_rewriter
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
